spring:
  application:
    name: task-pulse
    version: 1.0.0

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/mydb
    username: postgres
    password: postgres